version: '3.7'

services:
  web:
    build: .
    command: python /home/air/Workspace/Templates/Portfolio/manage.py runserver 0.0.0.0:8000
    environment:
      - ENVIRONMENT=development
      - SECRET_KEY='xi7v2!5p)%0b&k9a0_3b3dw=c+f^^%0)zrc)95(l^*)pa^-ar+'
    volumes:
      - .:/home/air/Workspace/Templates/Portfolio/
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'

volumes:
  postgres_data:
